# Generated by Django 5.2.3 on 2025-06-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0003_mytrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='user',
        ),
    ]
