# Generated by Django 5.2.3 on 2025-06-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0004_remove_travelplan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytrip',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
