# Generated by Django 5.2.3 on 2025-06-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0005_mytrip_number_of_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='picture_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
