# Generated by Django 5.2.3 on 2025-06-24 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0006_travelplan_description_travelplan_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytrip',
            name='travel_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelApp.travelplan'),
        ),
    ]
